### ISSUE TITLE
Haskell environment usage

### ISSUE THREAD

**Issue by roimekoi** [Javran/kantour#1] opened 2017-08-18 13:13 UTC
EDIT:
Never mind, manage to run already

.................
Hi sorry im not very familiar with haskell environment with stack
I saw you use
stack build && stack exec -- dropcalc '5.7' 10000 
in nga forum
when i execute in src folder main project folder, it will prompt error executable not found.

i try cmd to src/kantour folder and do stack ghci Dropcalc.hs, then it prompt > waiting for me to input value,

may i know how should i compile your project and cmd to which folder and just run command like you

stack build && stack exec -- dropcalc '5.7' 10000 

thanks and regards
happy farming, painful getting amagiri now

**Comment by Javran** [comment] 2021-05-22 23:15
Closing as the problem is already solved, also there's https://javran.github.io/dropcalc/ that you can run with browser now, no need for any Haskell stuff.

**Closed by Javran** 2021-05-22 23:15 UTC
